# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Go Build
        run: go build -v ./...

      - name: Go Test
        run: go test -v ./...

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up restcli
        run: curl -o restcli.zip -L -v https://github.com/restcli/restcli/releases/download/v2.0.1/restcli.zip && jar xvf restcli.zip

      - name: Http Test
        run: (./hadinfo &) && java -jar restcli.jar -e "test" api.http
